libm: Avoid `debug_assert_eq!` if `feature = "compiler-builtins"`
If `fmaf16` is exported, the existing version hits errors like:

    error: `compiler_builtins` cannot call functions through upstream monomorphizations; encountered invalid call from `core::fmt::num::<impl core::fmt::Debug for u64>::fmt` to `core::fmt::num::imp::<impl core::fmt::Display for u64>::fmt`
       --> library/core/src/fmt/num.rs:85:17
        |
     79 | / macro_rules! impl_Debug {
     80 | |     ($($T:ident)*) => {
     81 | |         $(
     82 | |             #[stable(feature = "rust1", since = "1.0.0")]
    ...   |
     85 | |                 fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        | |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...   |
     96 | |     };
     97 | | }
        | |_- in this expansion of `impl_Debug!`
    ...
    595 | / impl_Debug! {
    596 | |     i8 i16 i32 i64 i128 isize
    597 | |     u8 u16 u32 u64 u128 usize
    598 | | }
        | |_- in this macro invocation

Presumably this comes from the call to `panicking::assert_failed!` that
needs to be monomorphized. Avoid any formatting by using a plain
`debug_assert!` if we are building the crate as compiler-builtins.