ci: Update which targets build musl
Provide reasoning for skips, and enable thumb since this seems to work.
Also, change wasm32-unknown-unknown to be a proper build-only target.

The mentioned failures on MinGW are cases like:

    thread 'musl_edge_case_expf' (1728) panicked at libm-test\tests\compare_built_musl.rs:26:50:
    called `Result::unwrap()` on an `Err` value:
      input:    (0.0,)
      as hex:   (+0x0p+0,)
      as bits:  (0x00000000,)
      expected: 0.0                 +0x0p+0   0x00000000
      actual:   1.0                 +0x1.000000p+0   0x3f800000

    thread 'musl_edge_case_ceil' (1964) panicked at libm-test\tests\compare_built_musl.rs:26:50:
    called `Result::unwrap()` on an `Err` value:
      input:    (1.0000000000000002,)
      as hex:   (+0x1.0000000000001p+0,)
      as bits:  (0x3ff0000000000001,)
      expected: 1.0                 +0x1.0000000000000p+0   0x3ff0000000000000
      actual:   2.0                 +0x1.0000000000000p+1   0x4000000000000000

Our libm's results are correct, for some reason musl is off (something
about the fp environment on x86, or a different FLT_EVAL_MODE?)