test: Skip fdim bitwise NAN tests
We are seeing failures like this:

    ---- math::fdim::tests::check_f128 stdout ----

    thread 'math::fdim::tests::check_f128' (30393994) panicked at libm/src/math/fdim.rs:149:9:
    fdim(0xffff0000000000000000000000000000, 0x7fff8000000000000000000000000000) (-inf +qNaN(0x0000000000000000000000000000))
    l: 0xffff8000000000000000000000000000 (0xffff8000000000000000000000000000 -qNaN(0x0000000000000000000000000000))
    r: 0x7fff8000000000000000000000000000 (0x7fff8000000000000000000000000000 +qNaN(0x0000000000000000000000000000))
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


    failures:
        math::fdim::tests::check_f128

Which are caused by 23f834808a3f ("c-b: Preserve NaN signs in soft-float
addition") making it into the nightly toolchain. Skip these tests for
now to get CI passing again.

See <https://github.com/rust-lang/compiler-builtins/pull/1325> for a
possible fix.